name: PR Environment Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  pr_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up pull request environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_ISLAND_0DC928510 }}
          action: "close"
          deployment_environment: canary-${{ github.event.pull_request.number }}
          app_location: ""
          skip_app_build: true
          skip_api_build: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
